### ISSUE TITLE
What features would you like to see added to Meshblu?

### ISSUE THREAD

**Issue by kmariano** [octoblu/meshblu#102]
What features would you like to see us add to meshblu. Please add them in the comments

**Comment by brianehlert** [comment]
I would like to be able to forward messages.  With the option of using a Meshblu instance as a proxy / message forwarder.
This way I could use Meshblu to bridge between one subnet and another.  Such as a multi-tier application where the users can only interact with the front end servers and not directly with the database servers.
There are secure configurations where Gateblu might or might not be involved, but cannot bridge between two IP subnets, or is not appropriate to bridge.  But  Meshblu forwarder / proxy could bridge and route on behalf of multiple Gateblu instances.

**Comment by brianehlert** [comment]
The concept of a pool / resource pool / grouping of heterogeneous devices.
A way to associate devices.
It could be used to return a list of devices, to message a group of targeted devices (without knowing all of the individuals), to create a hierarchy of devices (parent / child) that is not a messaging based hierarchy.
The pool itself would be a device.

**Comment by iamruinous** [comment]
Message forwarding: https://developer.octoblu.com/docs/forwarding
Message webhooks: https://developer.octoblu.com/docs/forwarding-webhooks

**Comment by brianehlert** [comment]
My use of the term "forwarding" was more of a gateway.  Where a local Meshblu is a message gateway for larger Meshblu (such as the cloud service). 
More like an invisible enterprise proxy, or single enterprise message router / gateway concept.  Where the devices are still first class, directly addressable in Octoblu (for example).
So I have one point that I can secure for communications and not 100's of Gateblu's, or thousands of individual devices that are on the LAN.
