### ISSUE TITLE
Question: Is it possible to fetch an array of devices based on a number of UUIDs?

### ISSUE THREAD

**Issue by SamuelToh** [octoblu/meshblu#107]
Hi,

I was scanning through the meshblu documentation amd Readme.md file for examples on how I can query devices and subscribing to their events through a set of UUIDs and it seems like there is no way to do this? Please correct me if I am wrong on this. 

Not particularly important as I have got a work around for it by simply fetching all devices owned by the owner and then manually filtering through them. 

Cheers,
Sam

**Comment by chrismatthieu** [comment]
We have an API endpoint called MyDevices (https://meshblu-http.readme.io/docs/mydevices).  This endpoint returns all UUIDs that belong to an "owner" UUID.  You could then iterate through this array and subscribe to each of the UUIDs.
