### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by rjfv** [octoblu/meshblu#111]
Hello,

Do you have a wiki page or similar with versioned changes documented? I just need to know the differences between Meshblu server's versions, but I can't seem to find it...

Thanks in advance!

**Comment by fmonsanto** [comment]
+1, I'm using an older version and would like to be able to understand what has changed.

**Comment by luiscvalmeida** [comment]
+1

**Comment by JMGGarcia** [comment]
+1

**Comment by IvoPintodaSilva** [comment]
+1

**Comment by AndreDuarte00** [comment]
+1

**Comment by iamruinous** [comment]
We don't currently. We can do a much better job of this. Frankly, it was so quiet I didn't think anyone cared. 

We are also working on Meshblu 2.0 with a cleaner and more scalable architecture. I'll do some write ups on that as well.

**Comment by rjfv** [comment]
Thanks @iamruinous for your comment!

We're using Meshblu on a large-scale project, for Smart Cities, and we've noticed that our instance's performance decreases after processing thousands of events. Since we're using one of the earliest versions, we need to plan the update procedure quite thoroughly.

We've tried to use the latest version but, for example, it's no longer possible to send the device UUID as a parameter when registering a device. Therefore, we need a detailed changelog with all the version changes.

We're also very curious about the 2.0 version! ;)

**Comment by brianehlert** [comment]
@rjfv I have been working with keeping up with Meshblu changes for +12 months now.  And depending on how you have implemented and what behavior assumptions you are depending upon, you could have many issues when you approach upgrading.
During my time there have been significant changes that we have had to accommodate. Device registration is one of the smaller ones, the change in the message security model is the big one that I anticipate you will hit first.

**Comment by rjfv** [comment]
Thanks @brianehlert! Those are the sort of things I need to know in order to estimate correctly!

**Comment by iamruinous** [comment]
@rjfv unfortunately you'll have to look through the commit log if you want a detailed list of changes.

We have overcome many scaling issues with Meshblu and I'm happy to help you in any way that I can. Like @brianehlert a lot will depend on how you are using it. We have a gitter channel if you want to chat over there https://gitter.im/octoblu/meshblu.

**Comment by brianehlert** [comment]
As @iamruinous mentioned, you can chat with the team directly on Gitter.  And I am open to answering questions directly if you want to message me as well.

**Comment by rjfv** [comment]
One of the things I'm considering at the moment is to disable the use of `data.db` and `events.db` databases, @iamruinous @brianehlert, is that a simple way to do that and avoid ruining everything in Meshblu? :)

**Comment by chrismatthieu** [comment]
@rjfv I would love to learn more about your smart city project and Meshblu's role in it!  Can you hit me up on email? c@octoblu.com

**Comment by chrismatthieu** [comment]
@rjfv BTW, we have been thinking about deprecating the data and events APIs.  

Data may still exist but we would route its data through the data forwarders to your own data store rather than ours.  

Events was implemented before our pubsub capabilities.  We're not aware of anyone still using these endpoints...

We would love to get your feedback.

**Comment by iamruinous** [comment]
I've started to document Meshblu 2.0 in the wiki, there is still a long ways to go, but feedback is welcome.

https://github.com/octoblu/meshblu/wiki/Overview

**Comment by rjfv** [comment]
Thank you both @iamruinous and @chrismatthieu and sorry for the late reply! I'll write you with a bit more details and some feedback on your solution, please keep up the good work!

Happy holidays :)
