### ISSUE TITLE
Issues registering device over raw WebSocket

### ISSUE THREAD

**Issue by RickCarlino** [octoblu/meshblu#112]
I was transferring some older Socket.io code over to the newer raw WS interface and hit some `401` errors when trying to register:

```javascript

var ws = new WebSocket("wss://meshblu.octoblu.com/ws/v2");

ws.onopen = function() {
  ws.send(
      JSON.stringify(["register", {}])
      );
};

ws.onmessage = function(e) { console.dir(e.data); };

```

The following code snippet will return:

```
["error",{"message":"unauthorized","frame":["register",{}],"status":401}]
```

Did I do something wrong while registering or is this an internal issue? The code above is more or less a copy/paste job from the [documentation](https://meshblu-websocket.readme.io/docs/register), so I wasn't sure.

**ADDITIONAL INFO:** The snippet above does not appear to emit a "ready" event. Even if I just connect.

**Comment by iamruinous** [comment]
Fixed in 5a12501
