### ISSUE TITLE
Meshblu SW patents

### ISSUE THREAD

**Issue by drasko** [octoblu/meshblu#117]
@chrismatthieu I have spotted a series of patents filled for Meshblu: http://patents.justia.com/inventor/chris-matthieu

From what I can understand, these two concepts are protected by the patents:
 - Device identification and registration to the system using UUID and token
 - Device access right sharing using whitelists/blacklists and ownership

I am wondering how this can be possible, since whole world is using token-based authentication, and also whitelisting/blacklisting - i.e. allowing a user a certain amount of access rights on the resource - is not an unusual procedure.

In any case, I find Meshblu unusable for building open systems, as Citrix has now all the patent rights on the system architecture and authentication procedures, as well as on the procedures of resource sharing between devices.

I can not see how someone can build a private cloud based on these principles without obvious patent infringement :(

**Comment by brianehlert** [comment]
I am curious about your comments.
The presence of patents don't prevent you from building on top of the platform (meshblu) or using meshblu - whether private instances or the cloud service.
The patents prevent copying those mechanisms that were patented into some other product.

**Comment by chrismatthieu** [comment]
@drasko These patents were filed to protect Meshblu and the projects developed on top of Meshblu.

**Comment by drasko** [comment]
@brianehlert no - building an app which would include Meshblu inside in a closed-source commercial variant will not do. Code is MIT, so technically is possible, but since it is patent burdened you can not sell your solution

I doubt that you can even host your private Meshblu cloud. Especially if you close the source.

Imagine that you embed Meshblu in your closed-source commercial cloud and start selling GW or charging services for connecting devices. Who will tell if this is your code or Meshblu inside (note that you are not obliged to tell that it has a Meshblu inside)? In any case, your commercial solution will use patented approach.

@chrismatthieu I understand the intention, but I am still wondering how so obvious things like token-based authentication and resource whitelisting can be patented when it is so widely used in the industry - but these patents have been only filled and not yet granted. So they will potentially be rejected.

In any case, SW patents is something that open source community avoids and fights against, I hope that you are aware of that.

**Comment by iamruinous** [comment]
@chrismatthieu We should probably have a public non-aggression statement for Open Source projects.

@drasko the sad reality of the world is a defensive patent portfolio is a necessary evil. Many open source companies are faced with the same problem.

I spent many years fighting against software patents and I wish they did not exist, but for a commercial entity it is simply a matter of prudence to protect itself.

Also FYI, all 3 of the patents referenced above have been successfully granted.
