### ISSUE TITLE
Empty message frames coming back from server? 

### ISSUE THREAD

**Issue by RickCarlino** [octoblu/meshblu#124]
![socket_messages](https://cloud.githubusercontent.com/assets/1388608/13177372/4d1ae93a-d6de-11e5-8c34-0c09ff911cf9.png)

**NOTE:** The last two frames in that image work as expected. I left them in the screenshot to show that I am getting messages from the remote end without problems.

## Setup

 * A browser WebSocket client ("local") is connecting to a remote client that uses Socket.io ("remote").
 * Local is subscribed to remote and receiving messages from remote without any issues. :+1: 
 * Remote is sending messages to `devices: "*"`
 * Local is sending messages to `devices: "remote-uuid"`
 * Local receives broadcasts from remote device fine :+1: 

## Problems

 * Messages sent by local are not received by remote, despite being able to communicate in the opposite direction.

## Peculiarities?

 * Whenever local sends a `["message", {}]` frame, MeshBlu is echoing back a `["message", null]` frame. Is this expected behavior, or the response of a malformed message?
 * It appears that the `READY` response is not the same as the one [in the documentation](https://meshblu-websocket.readme.io/docs/identity). See image above to see actual response I am getting.

**Comment by RickCarlino** [comment]
It's as if I can't send messages directly to devices anymore. If they are subscribed to me and I send the message to `["*"]`, then the message arrives, no problem.

For example, this will get to my recipient, no problem:

```
["message",{"devices":["*"],"hello":"WORLD"}]
```

But this message will never arrive:

```
["message",{"devices":"ade3785c-fb6e-4f07-877a-ace9d03f9b3e","something":"different"}]
```

**Comment by brianehlert** [comment]
More a curious question than anything.
In your everyone message you are sending an array with one "*" within it.  In the one that you state won't arrive, it is not an array.
Typo?

**Comment by RickCarlino** [comment]
Tried that also. Still no luck

**Comment by virgilvox** [comment]
The device you are messaging has to have the messaging device in its whitelist in order for it to be allowed to message directly in that way.

**Comment by virgilvox** [comment]
Example:

```
conn.update({
      'sendWhitelist': ["uuid-of-the-thing-sending-messages"]
    });
```

**Comment by roryaronson** [comment]
@virgilvox we tried this with `["*"]` but that didn't change anything. Does it have to be a specific UUID?

**Comment by eternaltao** [comment]
Try add it into receiveWhitelist
message with ["*"]  means broadcast, must in receiveWhitelist
