### ISSUE TITLE
Why removed the API about the Data and Events?

### ISSUE THREAD

**Issue by tankerdream** [octoblu/meshblu#125]
Will API about Data and Events have new alternatives?

**Comment by chrismatthieu** [comment]
Yes, we are working on a something called Data Forwarders now. These will allow you to stream data in realtime to your own data stores.  This should be available in the next 2-3 weeks.

**Comment by iamruinous** [comment]
We've been slowly moving towards Meshblu 2.0 and decided not to port the Data and Events API forward. You can read more about Meshblu 2.0 at https://github.com/octoblu/meshblu/wiki/Overview.  Like @chrismatthieu said we will provide a much better alternative that will allow you to capture your data in any datastore that you like.

If you'd like to build something yourself now, you can use the [Server Side Subscriptions API](https://meshblu.readme.io/docs/subscriptions#) to capture messages sent to/from your devices and redirect them to a device that can then log those messages to any datastore you'd like.
