### ISSUE TITLE
having a lot of issues with the mongojs package

### ISSUE THREAD

**Issue by ryanrdl** [octoblu/meshblu#126]
I imagine this is entirely an issue with the configuration on my end but I have spent 2 days trying to just get "npm install" to work after cloning the meshblu repo.  I have gone through setting up my ssh keys and have reduced a number of the issues but I still can't get all the way through so I thought I would raise the red flag and see if anyone can point me in the right direction.

Trying to run this on windows...

$ npm -v
3.7.3

$ node -v
v5.9.1

$ ssh github.com
PTY allocation request failed on channel 0
Hi ryanrdl! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.

LitvakR@STP1COR3976LT MINGW64 /c/git/meshblu (master)
$ npm install
npm ERR! addLocal Could not install C:\Users\LitvakR\AppData\Local\Temp\npm-2971                                                                                                                                                                                               6-73ab7ada\git-cache-18ec995f\91f0c6848142246170d1b04bfc223ade67662d47
npm ERR! addLocal Could not install C:\Users\LitvakR\AppData\Local\Temp\npm-2971                                                                                                                                                                                               6-73ab7ada\git-cache-c21e7b30\91f0c6848142246170d1b04bfc223ade67662d47
npm ERR! git fetch -a origin (git@github.com:octoblu/mongojs.git) Permission denied (publickey).
npm ERR! git fetch -a origin (git@github.com:octoblu/mongojs.git) fatal: Could not read from remote repository.
npm ERR! git fetch -a origin (git@github.com:octoblu/mongojs.git)
npm ERR! git fetch -a origin (git@github.com:octoblu/mongojs.git) Please make sure you have the correct access rights
npm ERR! git fetch -a origin (git@github.com:octoblu/mongojs.git) and the repository exists.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code 128

$ npm install github:octoblu/mongojs#mongodb-core-workaround
npm ERR! addLocal Could not install C:\Users\LitvakR\AppData\Local\Temp\npm-27264-ab0968f7\git-cache-7dc64859\91f0c6848142246170d1b04bfc223ade67662d47
npm ERR! addLocal Could not install C:\Users\LitvakR\AppData\Local\Temp\npm-27264-ab0968f7\git-cache-9772be48\91f0c6848142246170d1b04bfc223ade67662d47
npm ERR! addLocal Could not install C:\Users\LitvakR\AppData\Local\Temp\npm-27264-ab0968f7\git-cache-718772ef\91f0c6848142246170d1b04bfc223ade67662d47
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "github:octoblu/mongojs#mongodb-core-workaround"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! path C:\Users\LitvakR\AppData\Roaming\npm-cache\mongojs\2.1.0\package.tgz
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall scandir

npm ERR! enoent ENOENT: no such file or directory, scandir 'C:\Users\LitvakR\AppData\Roaming\npm-cache\mongojs\2.1.0\package.tgz'
npm ERR! enoent ENOENT: no such file or directory, scandir 'C:\Users\LitvakR\AppData\Roaming\npm-cache\mongojs\2.1.0\package.tgz'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

$ git clone git@github.com:octoblu/mongojs.git
Cloning into 'mongojs'...
remote: Counting objects: 2459, done.
remote: Total 2459 (delta 0), reused 0 (delta 0), pack-reused 2459
Receiving objects: 100% (2459/2459), 405.98 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1390/1390), done.
Checking connectivity... done.

Hopefully that is enough info that someone can help me identify what else I need to do because I am all out of ideas...

**Comment by iamruinous** [comment]
We don't typically run on Windows. You may need to check with the mongojs team to see if they have any advice.

**Comment by iamruinous** [comment]
I also just updated our monogjs dependency to use the latest published version instead of our fork. It is no longer necessary.
