### ISSUE TITLE
Retaining messages

### ISSUE THREAD

**Issue by anhldbk** [octoblu/meshblu#131]
Would you please let me know if the feature of `retaining messages` is available when using `Meshblu` with:
- MQTT
- CoAP
- WebSocket

**Comment by iamruinous** [comment]
We've talked about some ways of accomplishing this, but nothing has been developed yet. The messaging system has focused on near real-time delivery so far. Adding offline delivery is very important. 

One possible way we've discussed is to forward your messages to another device/service that is optimized for message retention and on-demand delivery. That way the core messaging platform doesn't have to change, and people can implement their own if necessary.
