### ISSUE TITLE
config.token or environment variable TOKEN is required. Exiting.

### ISSUE THREAD

**Issue by 198700** [octoblu/meshblu#133]
Hello Team,
                  When i am running "node server.js --http"  command , we get " config.token or environment variable TOKEN is required. Exiting. " message. what is the problem . plz provide me some helping links that contains details steps.

Thank's & Regards
Pankaj

**Comment by royvandewater** [comment]
We have an explanation of what the Token does in the README, but it's not in an logical place :-(

https://github.com/octoblu/meshblu#docker

> A note about secrets: We require that whomever runs Meshblu to supply a text secret, in the form of the TOKEN environmnet variable, that we can use as a salt when hashing tokens. Not knowing this secret hinders a malicious user when creating a rainbow table to reverse the hashed tokens.

If you are running on Linux/OSX, then the command `env TOKEN="<any random string>" node server.js --http` should work. Just make sure that whatever random string you use is the same every time, or the device tokens will not be recognized as valid in Meshblu.
