### ISSUE TITLE
Can get Devices use regex？

### ISSUE THREAD

**Issue by NisaryXie** [octoblu/meshblu#145]
Can get Devices use regex？

**Comment by royvandewater** [comment]
It cannot, but I believe it may be possible using the Search API if we whitelist the `$regex` operator here: https://github.com/octoblu/meshblu-core-manager-device/blob/master/src/device-manager.coffee#L11

I'm not sure why it's not whitelisted already, so I want to check with @iamruinous before adding it in case it opens up a way to bypass someone's discover whitelist.
