### ISSUE TITLE
default config.js confusing and does not function without modifications

### ISSUE THREAD

**Issue by abhayghatpande** [octoblu/meshblu#77]
This issue has a 2-3 parts:
(1) The Readme file asks to copy config.js.sample to config.js. However, there already exists a config.js file in the repository and it is not clear if it is all right to overwrite/replace the existing config.js with the sample config.js file.

(2) After replacing the config.js file, some sections are marked as optional, while others are not. It appears that those not marked as optional are required, when in fact they may not be.

(3) Especially the section marked "this skynet cloud's uuid" is confusing because it seems to be required, but isn't. Moreover if the uuid and token fields are not commented out, it results in an error on launch.

A little cleanup and clarity on the config.js will probably help new users.

**Comment by chrismatthieu** [comment]
Sorry for the *very* delayed response. We now have a app.json that you can modify to meet your needs. 

You can optionally give your private Meshblu node a UUID and "connect" it to other Meshblu instances to form your own private mesh network.  These Meshblu nodes can relay messages across clouds to and from individual devices managed by other Meshblu clouds.

**Comment by abhayghatpande** [comment]
Thank you. Will check it out.
