### ISSUE TITLE
Redis password not used / enforced

### ISSUE THREAD

**Issue by brianehlert** [octoblu/meshblu#84]
I have an environment of Docker instances.  A Redis server, MongoDB server, ElasticSearch Server, and a Meshblu server.

I configure the Redis instance to require a password:  " sudo docker run -d -p 6379:6379 -v ~/redisdb:/data --name redis dockerfile/redis redis-server /etc/redis/redis.conf --requirepass P@ssw0rd "

I modify config.js with the same password:
  redis: {
    host: "xxx.xxx.xxx.xxx",
    port: "6379",
    password: "P@ssw0rd"
  }

When Meshblu starts and attempts to connect the following is thrown: " Ready check failed: NOAUTH Authentication required. Error: Ready check failed: NOAUTH Authentication required. " by Meshblu.

If I start the Redis server without enforcing a password then start Meshblu.  Meshblu starts without error.

The guess is that considering the behavior and the error, Meshblu is requiring NOAUTH of the Redis instance, instead of properly using the configured password for the Redis instance.

**Comment by mcinnes01** [comment]
@chrismatthieu 

Is there any update on this, I also get issues with Redis but with no password configured:

![image](https://cloud.githubusercontent.com/assets/877512/6158386/a2f4118c-b241-11e4-9635-848d5d5eaf90.png)

Many thanks

Andy

**Comment by brianehlert** [comment]
@mcinnes01 
Your redis server should not be asking for authentication and you should not be providing it in your configuration.
Just delete that password line.

**Comment by royvandewater** [comment]
I think we are trying to authenticate using the username and password here:

https://github.com/octoblu/meshblu/blob/76f2300b35c3e4e00256aaa4365105493205af78/lib/redis.js#L14

I have never tried it myself though, we run our Redis servers inside of VPN's so they are inaccessible, even without a password.

**Comment by brianehlert** [comment]
FYI - I am engaging @mcinnes01 on another issue and I don't think he is encountering this bug.  I think he has a different issue.

**Comment by chrismatthieu** [comment]
Closing old issues. Please reopen if needed...
