### ISSUE TITLE
Add Meshblu Event Streaming to Citrix Insight

### ISSUE THREAD

**Issue by chrismatthieu** [octoblu/meshblu#91]
Add Citrix Insight to logEvents.js

Documentation - http://mindtouch/Citrix_Insight_Services/Features/Datarrive/Interface_Specifications

**Comment by royvandewater** [comment]
We've been talking about changing how the Data Collectors work, one proposed idea:

If someone just wants access to sensor data, we create a forwarder that tries to query all available sensors it has permission to read from and auto-subscribes to them. That forwarder would then proxy all the data into a data store of some sort, so this is where it would enter Splunk, ElasticSearch, mongo, etc.

For all event streaming, we could create an alternate subscribe type (on top of the existing three), that subscribes to all events that device emits and would use the configureWhitelist to enforce the permissions. If a user wanted to collect the events of their devices, they would create a device exactly like the one mentioned in the previous paragraph, but instead use the new event subscribe (that doesn't exist yet)
