### ISSUE TITLE
Is there a "Verbose mode"?

### ISSUE THREAD

**Issue by RickCarlino** [octoblu/meshblu#94]
Sometimes I need to run an individual instance of MeshBlu and get detailed information about connections, messages sent / received etc.

Does MeshBlu have a verbose logging mode? I tried `-v`, but that didn't do the trick.

Thanks!

**Comment by iamruinous** [comment]
We use the [debug](https://www.npmjs.com/package/debug) package

`DEBUG=*` or `DEBUG=meshblu*`
