### ISSUE TITLE
Is it safe to install the latest version of mosca?

### ISSUE THREAD

**Issue by tonidy** [octoblu/meshblu#99]
Hi,

I have looked at issue #76 and I get this error when install meshblu, the mosca couldn't install zmq:

https://gist.github.com/tonidy/0012e1bef3b0a8724f3a

I know that zmq is optional dependency to mosca. But my question is if we install the latest version of mosca, is it safe or not?

thanks

**Comment by chrismatthieu** [comment]
The latest version of Mosca is safe to install.
